title: Pause Screen Gaming
theme: minima
author: Malaert64
email: malaert11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Delivering you one man's opinions and passions within the gaming world.

# social links
twitter_username: Malaert64 # DO NOT include the @ character, or else the build will fail!
github_username:  Malaert64 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
